#pragma once

#define IDI_APP_ICON 101
#define IDS_APP_TITLE 102

#define SCREENTRANS_VERSION_MAJOR 1
#define SCREENTRANS_VERSION_MINOR 1
#define SCREENTRANS_VERSION_PATCH 0
#define SCREENTRANS_VERSION_BUILD 0

#define SCREENTRANS_VERSION_TUPLE 1, 1, 0, 0
#define SCREENTRANS_VERSION_STRING "1.1.0.0\0"
